### PR TITLE
windows compatibility

### PR DESCRIPTION
**Pull request by DiMartinoXBMC**
great stuff, I'm gonna use it in my addon

### CODE REVIEW

**Comment by izderadicka** [comment]
Thanks,   can we do better on signal handling in Windows? on_exit function is doing few important things to assure clean closure of program.

**Comment by izderadicka** [comment]
BTW - these is already Kodi addon which works on Linux - https://github.com/izderadicka/btclient-kodi-addon.
I'm not very much into Windows :-)

**Comment by DiMartinoXBMC** [comment]
Wow, didin't see that kodi addon. btclient is great, so I'm replacing my current player in Torrenter (mostly because of seeking)
There are no signals in windows, this is unix thing. I also made some changes, made it work with no_depricated python-libtorrent build, can pull-request it.

**Comment by izderadicka** [comment]
Actually there is some support for signals on Win - this is from signal module documentation:

On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. A ValueError will be raised in any other case.

So theoretically at lest SIGINT can work - however I've seen some comments that its support is problematic in Win.  

I'll merge changes.

**Pull request merged**
